### PR TITLE
fix ID-48 and other problems of validation for email adding

### PR DESCRIPTION
**Pull request by Plypy**
Due to carelessness, I forgot to validate the email-adding thoroughly.

So user may add duplicate emails and emails with plus(+).

### CODE REVIEW

**Comment by Plypy** [comment]
Added commit that set all the newly-added email as lowercase only.

Also be careful, when I was testing this, I found that mongoose won't fire the setter for array when you modify a document. so the `arrToLowerCase` won't be called. It seems to be a bug, and not fixed in the latest version(3.8.14).

Be careful about the case of emails.

**Comment by elliottwilliams** [comment]
So does `arrToLowerCase` have to be called manually when adding/modifying email addresses? And if so, are you calling it already?

Thanks!

**Comment by Plypy** [comment]
I've asked this issue on the Google Groups, and the author said. If we want to call the setter of an array, we should use `schema.set(path,...)`.

Otherwise, it will skip the setter. And I've tested it, it's true, but the validator will still be called.. it's odd.

Anyway, I didn't do that in this patch, I just made sure that the email added is lowercase. What's to say, I added this, [here](https://github.com/openmrs/openmrs-contrib-id/pull/14/files#diff-9f89984fcbc49f4e320e97145a022b40R14)

```
req.body.newEmail = req.body.newEmail.toLowerCase();
```

**Comment by elliottwilliams** [comment]
Everything looks good to me! Merging

**Pull request merged**
