### PR TITLE
GCI-31 - Navigation bar revamp

### PR DESCRIPTION
**Pull request by Izaron**
Ticket: http://issues.openmrs.org/browse/GCI-31

### CODE REVIEW

**Comment by Izaron** [comment]
I done this while the other task in review. Thanks!

**Comment by elliottwilliams** [comment]
Ok, thanks. Just an FYI, you are only allowed to work on one task at a time per the GCI rules: https://www.google-melange.com/gci/document/show/gci_program/google/gci2014/help_page#moreone

Once you are granted a claim on this task, please include it here and I'll review your work.

**Comment by Izaron** [comment]
@elliottwilliams
Sorry about that. I think that now none of the students will not violate this rule :)
Melange task: https://www.google-melange.com/gci/task/view/google/gci2014/5666446822604800

**Comment by elliottwilliams** [comment]
This is a good start, but I think you could do a little more to go along with the wireframes.

I would encourage using bootstrap HTML components in your work. Justified buttons groups (http://getbootstrap.com/components/#btn-groups-justified) look like they would work well for our design.

Could you try modifying the link html to use these bootstrap buttons? We already have bootstrap loaded in every page, so you don't need to add any resources.

Thanks, and let me know if you have any questions!

**Pull request closed without merging**
