### PR TITLE
GCI-34: Sign Up Page

### PR DESCRIPTION
**Pull request by glowcone**
Here is the modified sign up page according to the new wireframe.

Imgur

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Great, thanks for your contribution. I have a couple suggestions, but I think this is nearly complete:
- Could you keep the country field in place? It's actually a [spam honeypot](http://www.dexmedia.com/blog/honeypot-technique/), so it should stay on the page but be invisible to the user :) You can remove that "Removed code to hide country" commit by using a git reabse (https://stackoverflow.com/questions/1338728/delete-commits-from-a-branch-in-git)
- Instead of adding that `.bg-box` class, use a panel as specified in the style guide: https://id.openmrs.org/styleguide
- Rather than adding an `<h1>` header into the signup view, customize the `headline` variable on the page instead. You can add any HTML into the headline variable.

Hope this helps, and thank you for your work thus far!

**Comment by glowcone** [comment]
Nitrous messed up my code, now signup.ejs is completely blank.

screen shot 2014-12-05 at 10 44 09 pm

So I pasted in the previous code... and it refused to save. Pressing the save button does nothing, neither does Ctrl-S.
I restarted the box, switched browsers, switched computers, but it still does not show signup.ejs nor let me save. Other files are fine.
Previewing it gives me an error

screen shot 2014-12-05 at 10 50 27 pm

How can I fix this?
Also, may I get an extension? I have fixed all but the header (which needs signup.ejs).

EDIT:
Now several files are grayed out.
screen shot 2014-12-05 at 10 57 30 pm

**Comment by elliottwilliams** [comment]
Sure, I gave you another day. Sorry about nitrous. The best I can suggest is to checkout the last version from git: `git checkout signup.ejs`

**Comment by glowcone** [comment]
Checkout doesn't work either... :(

**Comment by elliottwilliams** [comment]
Hm, check your disk space. I know if you go into the settings panel of the Nitrous box it'll tell you. Running MongoDB on these boxes sometimes makes space a little tight :\

**Comment by glowcone** [comment]
Ohh! that must be why.
screen shot 2014-12-06 at 4 11 55 pm

---

Now it works! Made the storage 2500 mb.

**Comment by glowcone** [comment]
Can you please review this task on GCI? :)
(The new code is here: https://github.com/openmrs/openmrs-contrib-id/pull/29)

**Pull request closed without merging**
